#!/usr/bin/env python3

'''
  Source code provider

  Copyright 2013-2018 RIKEN
  Copyright 2018-2022 Chiba Institute of Technology

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
'''

__author__ = 'Masatomo Hashimoto <m.hashimoto@stair.center>'

import os
import sys
from common import BASE_DIR

import cgi

###

HEADER = b'Content-Type: text/plain\n\n'


form = cgi.FieldStorage()

path = form.getvalue('path', '???')

src_path = os.path.join(BASE_DIR, path)

src = None

try:
    with open(src_path, 'rb') as f:
        src = f.read()

except Exception as e:
    src = str(e).encode('utf-8')

sys.stdout.buffer.write(HEADER)
sys.stdout.buffer.write(src)
