#!/usr/bin/env python3

'''
  Source code viewer

  Copyright 2013-2018 RIKEN
  Copyright 2018-2020 Chiba Institute of Technology

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
'''

__author__ = 'Masatomo Hashimoto <m.hashimoto@stair.center>'

from urllib.parse import urlencode
from common import BASE_URL

HTML_TEMPL = '''Content-Type: text/html

<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html version="-//W3C//DTD XHTML 1.1//EN"
      xmlns="http://www.w3.org/1999/xhtml"
      xml:lang="en"
      >
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>SourceCodeViewer</title>
<link rel="stylesheet" href="%(base_url)s/codemirror/lib/codemirror.css"></link>
<link rel="stylesheet" href="%(base_url)s/codemirror/addon/dialog/dialog.css"></link>
<link rel="stylesheet" href="%(base_url)s/js/scv/scv.css"></link>
<link rel="stylesheet" type="text/css" href="%(base_url)s/demo.css"/>
<script type="text/javascript" src="%(base_url)s/jquery.min.js"></script>
<script type="text/javascript" src="%(base_url)s/codemirror/lib/codemirror.js"></script>
<script type="text/javascript" src="%(base_url)s/codemirror/addon/scroll/simplescrollbars.js"></script>
<script type="text/javascript" src="%(base_url)s/codemirror/addon/scroll/annotatescrollbar.js"></script>
<script type="text/javascript" src="%(base_url)s/codemirror/addon/dialog/dialog.js"></script>
<script type="text/javascript" src="%(base_url)s/codemirror/addon/search/searchcursor.js"></script>
<script type="text/javascript" src="%(base_url)s/codemirror/addon/search/search.js"></script>
<script type="text/javascript" src="%(base_url)s/codemirror/addon/selection/mark-selection.js"></script>
<script type="text/javascript" src="%(base_url)s/codemirror/addon/fold/foldcode.js"></script>
<script type="text/javascript" src="%(base_url)s/codemirror/addon/fold/foldgutter.js"></script>
<script type="text/javascript" src="%(base_url)s/codemirror/addon/fold/brace-fold.js"></script>
<script type="text/javascript" src="%(base_url)s/codemirror/addon/fold/comment-fold.js"></script>
<script type="text/javascript" src="%(base_url)s/codemirror/addon/fold/indent-fold.js"></script>
<script type="text/javascript" src="%(base_url)s/codemirror/mode/python/python.js"></script>
<script type="text/javascript" src="%(base_url)s/codemirror/mode/verilog/verilog.js"></script>
<script type="text/javascript" src="%(base_url)s/codemirror/mode/clike/clike.js"></script>
<script type="text/javascript" src="%(base_url)s/js/fortran.js"></script>
<script type="text/javascript" src="%(base_url)s/js/common.js"></script>
<script type="text/javascript" src="%(base_url)s/js/scv/scv.js"></script>

<script type="text/javascript">
var scv = new SourceCodeViewer();
</script>
</head>

<body>

<div id="head">
<h1>Source Code View</h1>


<h3><a href="%(src)s" target="_blank">%(path)s</a> %(pos)s from %(ver)s</h3>


<div id="view"></div>

<div id="tail">
<table>
<tr>
<td width="100%%"><span id="legend"></span></td>
<td>
<div >
<form>
<input type="button" value="Close" onClick="javascript:window.close();">
</form>
</div>
</td>
</tr>
</table>
</div>

<script type="text/javascript">
$(document).ready(function(){
var url = "%(url)s";
var lang = %(lang)s;
var view = document.getElementById("view");
scv.show(url, view, lang, %(startl)s, %(endl)s, %(aref_ranges)s);
})
</script>

</body></html>
'''


import re
import json

GITWEB_H_PAT = re.compile(r'/gitweb/\?.*h=(?P<h>[^;]+).*')
GITWEB_P_PAT = re.compile(r'/gitweb/\?.*p=(?P<p>[^;]+).*')
GITWEB_F_PAT = re.compile(r'/gitweb/\?.*f=(?P<f>[^;]+).*')
GITWEB_HB_PAT = re.compile(r'/gitweb/\?.*hb=(?P<hb>[^;]+).*')


import cgi
form = cgi.FieldStorage()

# proj = form.getvalue('proj', '???')

ver = form.getvalue('ver', '???')

path = form.getvalue('path', None)

lang = form.getvalue('lang', None)

src = form.getvalue('src', '???')

startl = form.getvalue('startl', '0')
startc = form.getvalue('startc', '0')

endl = form.getvalue('endl', '0')
endc = form.getvalue('endc', '0')

aref_ranges = form.getvalue('aref_ranges', '[]')

params = {
    'ver': ver,
    'src': src,
    'startl': startl,
    'startc': startc,
    'endl': endl,
    'endc': endc,
    }


if startl == '0' and startc == '0':
    pos = ''
else:
    pos = '%sL,%sC' % (startl, startc)


params['pos'] = pos


m = GITWEB_H_PAT.match(src)

if src.startswith('/gitweb'):
    url = src
else:
    url = 'getsrc?%s' % urlencode({'path':src})

params['url'] = url

m_p = GITWEB_P_PAT.match(src)
m_f = GITWEB_F_PAT.match(src)
m_hb = GITWEB_HB_PAT.match(src)


if m_p and m_f and m_hb:
    if path is None:
        path = m_f.group('f')
    ssrc = '/gitweb/?%s' % urlencode({'p': m_p.group('p'),
                                      'a': 'blob_plain',
                                      'f': path,
                                      'hb': m_hb.group('hb'),
                                      })
    params['src'] = ssrc
    params['path'] = path
else:
    if path is None:
        path = src
    params['src'] = url
    params['path'] = path


if lang:
    params['lang'] = '"%s"' % lang
else:
    params['lang'] = 'getLang("%(path)s")' % params

params['aref_ranges'] = aref_ranges
params['base_url'] = BASE_URL

print(HTML_TEMPL % params)
