#!/usr/bin/env python3

'''
  Mongodb status

  Copyright 2013-2018 RIKEN
  Copyright 2018-2020 Chiba Institute of Technology

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
'''

__author__ = 'Masatomo Hashimoto <m.hashimoto@stair.center>'

import sys
import json

from common import DEFAULT_USER, compute_state

###

import cgi
import cgitb
cgitb.enable()

form = cgi.FieldStorage()

user = form.getvalue('user', DEFAULT_USER)
proj = form.getvalue('proj', None)
ver = form.getvalue('ver', None)

data = {}

if proj and ver:
    data = compute_state(user, proj, ver)

else:
    if proj:
        mesg = 'ver not specified'
    elif ver:
        mesg = 'proj not specified'
    else:
        mesg = 'proj and ver not specified'

    data['failure'] = mesg


HEAD = 'Content-Type: application/json'

print(HEAD)
print('')
sys.stdout.write(json.dumps(data))
