#
# Copyright 2013-2017 RIKEN
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Author: Masatomo Hashimoto <m.hashimoto@riken.jp>


DEFINE input:inference "ont.cpi"

PREFIX fb:      <http://codinuum.com/fb/>
PREFIX ent:     <http://codinuum.com/fact/entity/>
PREFIX variant: <http://codinuum.com/fact/version/variant/>
PREFIX rel:     <http://codinuum.com/fact/version/release/>
PREFIX svn:     <http://codinuum.com/fact/version/svn/revision/>
PREFIX src:     <http://codinuum.com/ontologies/2012/10/source-code-entity#>
PREFIX ver:     <http://codinuum.com/ontologies/2012/10/versioning#>
PREFIX f:       <http://codinuum.com/ontologies/2013/05/fortran-entity#>

INSERT {
  ?ent f:signature ?sig .
}
WHERE {

  {
    SELECT DISTINCT ?ent 
    (GROUP_CONCAT(?value0; SEPARATOR=";") AS ?value)
    (GROUP_CONCAT(?digest0; SEPARATOR=";") AS ?digest)
    (GROUP_CONCAT(?name0; SEPARATOR=";") AS ?name)
    WHERE {

      ?ent a f:Expr ;
           f:inDoConstruct ?loop .
      {
        ?ent f:value ?value0 .
      }
      UNION
      {
        ?ent src:treeDigest ?digest0 .
      }
      UNION
      {
        ?ent f:name ?name0 .
      }

    } GROUP BY ?ent
  }

  BIND (IF(STRLEN(?value)>0, ?value, IF(STRLEN(?digest)>0, ?digest, ?name)) AS ?sig)

}
